create table if not exists public.bixo_en_or_state (
  id text primary key,
  state jsonb not null,
  revision bigint not null default 0,
  updated_at timestamptz not null default now(),
  updated_by text
);

alter table public.bixo_en_or_state
  add column if not exists revision bigint not null default 0,
  add column if not exists updated_by text;

create table if not exists public.bixo_en_or_state_history (
  id bigint generated by default as identity primary key,
  state_id text not null,
  revision bigint not null,
  state jsonb not null,
  created_at timestamptz not null default now(),
  created_by text,
  reason text
);

alter table public.bixo_en_or_state enable row level security;
alter table public.bixo_en_or_state_history enable row level security;

drop policy if exists "Public read bixo_en_or_state" on public.bixo_en_or_state;
create policy "Public read bixo_en_or_state"
on public.bixo_en_or_state for select
using (true);

drop policy if exists "Public write bixo_en_or_state" on public.bixo_en_or_state;

drop policy if exists "Public read bixo_en_or_state_history" on public.bixo_en_or_state_history;
create policy "Public read bixo_en_or_state_history"
on public.bixo_en_or_state_history for select
using (true);

drop policy if exists "Public write bixo_en_or_state_history" on public.bixo_en_or_state_history;

create or replace function public.save_bixo_en_or_state(
  p_id text,
  p_state jsonb,
  p_expected_revision bigint,
  p_client_id text,
  p_reason text default 'save'
)
returns table(saved boolean, conflict boolean, revision bigint, state jsonb)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.bixo_en_or_state%rowtype;
  next_revision bigint;
begin
  select *
    into current_row
    from public.bixo_en_or_state
   where id = p_id
   for update;

  if not found then
    next_revision := 1;

    insert into public.bixo_en_or_state (id, state, revision, updated_at, updated_by)
    values (p_id, p_state, next_revision, now(), p_client_id);

    insert into public.bixo_en_or_state_history (state_id, revision, state, created_by, reason)
    values (p_id, next_revision, p_state, p_client_id, coalesce(p_reason, 'initial'));

    saved := true;
    conflict := false;
    revision := next_revision;
    state := p_state;
    return next;
    return;
  end if;

  if coalesce(p_expected_revision, 0) <> current_row.revision then
    saved := false;
    conflict := true;
    revision := current_row.revision;
    state := current_row.state;
    return next;
    return;
  end if;

  next_revision := current_row.revision + 1;

  update public.bixo_en_or_state
     set state = p_state,
         revision = next_revision,
         updated_at = now(),
         updated_by = p_client_id
   where id = p_id;

  insert into public.bixo_en_or_state_history (state_id, revision, state, created_by, reason)
  values (p_id, next_revision, p_state, p_client_id, coalesce(p_reason, 'save'));

  saved := true;
  conflict := false;
  revision := next_revision;
  state := p_state;
  return next;
end;
$$;

grant execute on function public.save_bixo_en_or_state(text, jsonb, bigint, text, text) to anon, authenticated;
